let selected="Scizor",tab="Summary",filter="all";const $=s=>document.querySelector(s),grid=$("#grid"),detail=$("#detail");
function sprite(m){return m.sprite}
function baseSummary(m){
 const info=CHAMPIONS_INFO[m.name];
 return `<h3>Base / Champions Summary</h3><div class="panel">${info.forms.map(f=>`<div class="card wide"><label>${f.name}</label><div class="chips">${f.types.map(t=>`<span class="chip">${t}</span>`).join("")}</div><p class="note" style="margin-bottom:0"><strong>Available abilities:</strong> ${f.abilities.join(" / ")}</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:12px">${Object.entries(f.stats).map(([stat,value])=>`<div class="card"><label>${stat}</label><b>${value}</b></div>`).join("")}</div><p class="note">Base stat total: <strong>${f.total}</strong></p></div>`).join("")}</div><p class="note"><a href="${info.source}" target="_blank" rel="noopener noreferrer" style="color:#70e5ff">Champions Pokédex reference</a> · Checked ${info.checked}</p><h3>Your Pokémon</h3>`;
}
function renderGrid(){let q=$("#search").value.toLowerCase();let mons=ROSTER.filter(m=>(filter==="all"||filter==="andes"&&m.andes||filter==="builds"&&BUILDS[m.name])&&m.name.toLowerCase().includes(q));$("#shown").textContent=mons.length;grid.innerHTML=mons.map(m=>`<button class="mon ${m.name===selected?"selected":""}" data-name="${m.name}"><img src="${sprite(m)}" alt="${m.name}"><small>${m.name}</small>${m.andes?'<i class="teamdot"></i>':""}</button>`).join("");grid.querySelectorAll(".mon").forEach(b=>b.onclick=()=>{selected=b.dataset.name;renderGrid();renderDetail()})}
function renderDetail(){const scrollTop=detail.scrollTop;let m=ROSTER.find(x=>x.name===selected)||ROSTER[0],b=BUILDS[m.name];let tabs=["Summary","Builds","Notes","Compare"];let content;
if(tab==="Summary") content=baseSummary(m)+personalSummary(m,b);
else if(tab==="Builds") content=personalMoves(b)+`<p class="note">Current build confirmed from your screenshot on ${b.confirmed}.</p>`+historySummary(b);
else if(tab==="Notes") content=`<div class="card wide"><label>Current build source</label><div class="note">Screenshot supplied ${b.confirmed}. Items and team assignments are not shown in these screenshots. Trial days are recorded as shown at capture.</div></div>`+historySummary(b);
else content=`<div class="card wide muted">Compare workspace reserved for head-to-head build and role comparisons.</div>`;

detail.innerHTML=`<div class="hero"><img class="portrait" src="${sprite(m)}"><div><div class="dex">DEX #${String(m.dex).padStart(4,"0")}</div><h2>${m.name.toUpperCase()}</h2><p class="note">${m.form} · ${m.gender}</p><div class="chips">${m.type.split(" / ").map(t=>'<span class="chip">'+t+'</span>').join("")}${m.andes?'<span class="chip">THE ANDES</span>':""}</div></div></div><div class="tabs">${tabs.map(t=>'<button class="tab '+(tab===t?"active":"")+'" data-tab="'+t+'">'+t+'</button>').join("")}</div>${content}`;detail.scrollTop=scrollTop;detail.querySelectorAll(".tab").forEach(x=>x.onclick=()=>{tab=x.dataset.tab;renderDetail()})}
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;renderGrid()});$("#search").oninput=renderGrid;renderGrid();renderDetail();

function personalMoves(b){return `<div class="card wide"><label>Current confirmed moves</label><div class="moves">${b.moves.map(move=>`<div class="move">${move}</div>`).join("")}</div></div>`;}
function personalSummary(m,b){
 const card=(label,value)=>`<div class="card"><label>${label}</label><b>${value}</b></div>`;
 const rows=Object.entries(b.stats).map(([stat,value])=>`<tr><th scope="row" style="text-align:left;padding:6px">${stat}</th><td style="text-align:right;padding:6px">${value}</td><td style="text-align:right;padding:6px">${b.training[stat]}</td></tr>`).join("");
 return `<p class="note">Confirmed from screenshot · ${b.confirmed}</p><div class="panel">${card('Recruitment status',m.status)}${card('Team',m.andes?'The Andes':'Unassigned / history')}${card('Your chosen ability',b.ability)}${card('Nature / stat alignment',b.nature)}${card('Form',m.form)}${card('Gender',m.gender)}<div class="card wide"><label>Held item</label><b>${b.item}</b></div><div class="card wide"><label>Your stats and training</label><table style="width:100%;font-size:12px;border-collapse:collapse"><thead><tr><th style="text-align:left;padding:6px">Stat</th><th style="text-align:right;padding:6px">Current value</th><th style="text-align:right;padding:6px">Training points</th></tr></thead><tbody>${rows}</tbody></table><p class="note">Training points used: ${Object.values(b.training).reduce((a,n)=>a+n,0)} · Values copied directly from the screenshot.</p></div>${personalMoves(b)}</div>`;
}
function historySummary(b){return (b.history||[]).map(h=>`<details class="card" style="margin-top:12px"><summary>Earlier recorded build</summary><p class="note">${h.label}</p><p class="note">Ability: ${h.ability}<br>Nature: ${h.nature}<br>Spread: ${h.ev}<br>Item: ${h.item}<br>Role: ${h.role}</p><div class="moves">${h.moves.map(move=>`<div class="move">${move}</div>`).join("")}</div><p class="note">${h.notes}</p></details>`).join("");}
